### PR TITLE
Add SearchApi as a Web Search Tool

### PR DESCRIPTION
**Pull request by SebastjanPrachovskij**
Added [SearchApi](https://www.searchapi.io/) tool.

The end user can change the search engine used on the SearchApi side via the engine parameter. Organic results share the same structure across all existing and upcoming SERP engines, so we will always have a title, snippet, and link. Google, Bing, Baidu, Google News, Bing News, Google Videos, Google Scholar, and Google Patents are already supported. Yandex and Yahoo are coming soon as well.

SearchApi is committed to supporting open-source integrations. Please feel free to mention [@SebastjanPrachovskij](https://github.com/SebastjanPrachovskij) for any future PR reviews related to SearchApi. We would be glad to help.

### CODE REVIEW

**Comment by nickscamara** [comment]
Hey @SebastjanPrachovskij thank you for the pr! We will check it out soon!

**Comment by SebastjanPrachovskij** [comment]
Hey @nickscamara 

I just wanted to follow up on the status of my pull request. 

I would appreciate any feedback or suggestions for the next steps whenever you can.

**Comment by nickscamara** [comment]
Hey @SebastjanPrachovskij, sorry about the delay. PR itself looks good! Could you email us a test key to test and play around with it? If you could send it to hello@firecrawl.com that would be amazing. Thank you!

**Comment by SebastjanPrachovskij** [comment]
Hey @nickscamara 

Just sent you an email.

**Comment by SebastjanPrachovskij** [comment]
Hey @nickscamara 

Just pinging to follow up. 😄

**Comment by nickscamara** [comment]
Hey @SebastjanPrachovskij sorry for the delay, will try to get that in our next bigger release. Thanks!

**Comment by SebastjanPrachovskij** [comment]
Hey @nickscamara,

Sent you another email (to [hello@firecrawl.com](mailto:hello@firecrawl.com)) with the test key.

**Pull request merged**
