### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by swyxio**
updated to offer a video guide.

### CODE REVIEW

**Comment by nickscamara** [comment]
Thanks @swyxio!

**Comment by nickscamara** [comment]
- [ ] Add to the docs (@rafaelsideguide)

**Comment by rafaelsideguide** [comment]
> * [x]  Add to the docs (@rafaelsideguide)

https://github.com/hellofirecrawl/docs/pull/35

**Comment by nickscamara** [comment]
Thanks @rafaelsideguide!

**Pull request merged**
