### PR TITLE
Playwright service bugs #222  #179  #197

### PR DESCRIPTION
**Pull request by mattjoyce**
There are a few things addressed in this patch.
For self host, this stops the constant scraper fallback, and improve reliability of the playwright response.

### CODE REVIEW

**Comment by nickscamara** [comment]
Awesome @mattjoyce will take a look at it soon.

ref #222 #179 #197

**Comment by JakobStadlhuber** [comment]
Bildschirmfoto 2024-06-03 um 22 10 35

#179 is still present

**Comment by mattjoyce** [comment]
@JakobStadlhuber that's not the same error.
Previously it was a Playwright 404, which this patch addresses.

agree you do still have an issue, can you update the issue thread.

**Comment by rafaelsideguide** [comment]
- [ ] merge
- [ ] publish (@nickscamara)

**Comment by rafaelsideguide** [comment]
I did an update on main to fix `scrapWithPlaywright` function (`wait` > `wait_after_load` parameter on `single_url.ts` file)

**Pull request merged**
