### PR TITLE
[Docs] Updating docs

### PR DESCRIPTION
**Pull request by rafaelsideguide**

### CODE REVIEW

**Comment by nickscamara** [comment]
Is this related to #430?

**Comment by rafaelsideguide** [comment]
@nickscamara no. It's related to these draft issues:
Captura de Tela 2024-07-18 às 08 51 58

**Comment by rafaelsideguide** [comment]
closes #431 #430 https://github.com/hellofirecrawl/docs/issues/10 https://github.com/hellofirecrawl/docs/issues/10 https://github.com/hellofirecrawl/docs/issues/6 https://github.com/hellofirecrawl/docs/issues/7 https://github.com/hellofirecrawl/docs/issues/8

**Review by nickscamara — APPROVED** [review]
lgtm

**Pull request merged**
