### PR TITLE
[Feat]: Add RUST SDK client for firecrawl API 

### PR DESCRIPTION
**Pull request by Sanix-Darker**
## WHAT

Writing the rust sdk client for firecrawl.

## WHY

Linked to : https://github.com/mendableai/firecrawl/issues/369

## TODO

- [x] write the rust version based on python-sdk interface.
- [x] make the `example.rs` rust code.
- [x] add rust lib tests.
- [x] publish the rust lib (for now with my crate.io account, may be changed later).
- [x] make the README.md documentation.
- [ ] add github action for tests (mocked, not tested).
- [ ] add github action for the publisher (mocked, not tested..
- [ ] add github action for fly (mocked, not tested).

## DEMO

https://github.com/mendableai/firecrawl/assets/22576758/29629f0d-b8eb-4205-9171-b4044bf13f77

### CODE REVIEW

**Comment by nickscamara** [comment]
So excited for this!!!

**Review by mogery — COMMENTED** [review]
Looking great so far! Will be reviewing this further when progress is made :)

**Comment by nickscamara** [comment]
Anything you need help with this to get it to the finish line? @Sanix-Darker

**Comment by Sanix-Darker** [comment]
@nickscamara , nope, all good, I will find some times at the end of the week to push some progress

**Comment by Sanix-Darker** [comment]
Hello @nickscamara , @mogery , 
At this point, i think it should be good for now, the lib, the example and tests are running pretty fine on my end, but am unable to 100% verify everything for the github actions part.

So maybe a maintainer could complete / fix that on later PR ?
Or do you prefer, i remove everything related to github action from this PR ?

Overall am open to a review and will update as soon as possible.

NOTE: i hosted the lib here : https://crates.io/crates/firecrawl_rs

**Comment by nickscamara** [comment]
This is super awesome! I'm so excited. Thank you! @mogery can you review and help get this to the finish line? tkss

**Comment by mogery** [comment]
Hey there, thanks for all the work! Looks good at a glance, I'll dive a bit deeper into it this week and get it reviewed.

**Comment by nickscamara** [comment]
@mogery can we get this merged this week?

**Comment by ericciarla** [comment]
Hey @Sanix-Darker, this is still in review. Do you mind opening a PR on [our docs](https://github.com/hellofirecrawl/docs)?

Just like we have for the [other SDKs](https://github.com/hellofirecrawl/docs/tree/main/sdks). Thanks!

**Comment by rafaelsideguide** [comment]
@nickscamara I added the env variable on this repo settings for publishing. Should be good to merge.

**Comment by Sanix-Darker** [comment]
Hello @rafaelsideguide / @nickscamara 
Sorry for the delay in replay, I had issues with my computer all this time, all fixed now.

Do you still need me on this PR ?
thanks.

**Comment by Sanix-Darker** [comment]
An invitation was sent for you @rafaelsideguide  using your GitHub username.

**Comment by rafaelsideguide** [comment]
Hey @Sanix-Darker, I think we're good. I'm merging this one and currently working on the v1 integration for this SDK.

**Pull request merged**
