### PR TITLE
[Feat] Add Go SDK implementation

### PR DESCRIPTION
**Pull request by KentHsu**
# Description

This PR add go-sdk based on js-sdk, python-sdk and rust-sdk implementations.

## Issue reference

Please reference the issue this PR will close: #481 

## Checklist

- [x] Implement firecrawl.go
- [x] Add tests for firecrawl.go
- [x] Add examples for go-sdk
- [x] Add README.md
- [x] Update GitHub Action workflow

### CODE REVIEW

**Comment by KentHsu** [comment]
@nickscamara @rafaelsideguide I hope this PR can be a good start for Firecrawl go-sdk implementation. In addition to the implementations in other SDK, I also added a method and some tests for the [cancel job API](https://docs.firecrawl.dev/api-reference/endpoint/crawl-cancel) since it's in the API reference. Please let me know if there's anything you want to update. Thank you

**Comment by nickscamara** [comment]
This is super awesome @KentHsu! Thank you so much!!! We will review it this week! 🚀 

@adayNU feel free to take a look as well.

**Comment by ericciarla** [comment]
Hey @KentHsu, we are still reviewing. Do you mind opening a PR on [our docs](https://github.com/hellofirecrawl/docs)?

Just like we have for the [other SDKs](https://github.com/hellofirecrawl/docs/tree/main/sdks).

Thank you!

**Comment by KentHsu** [comment]
Hi @ericciarla, Sure! I'll open a PR there for documenting Go SDK.

**Comment by rafaelsideguide** [comment]
Hey @KentHsu I did a review and a commit with some small improvements. Could you take a look? If there's no more changes to be done I think we can merge it 🎉

**Comment by KentHsu** [comment]
Hi @rafaelsideguide, thank you for reviewing this PR! Just one change I would like confirm with you. In `monitorJobStatus`, `makeRequest` already retries 3 times since we pass `withRetries(3)` to it. Do we still want to add `attempts` here for retrying?

**Comment by rafaelsideguide** [comment]
@KentHsu the problem is that the `monitorJobStatus` function is throwing the error `crawl job completed but no data was returned`. This occurs because the request is faster than Firecrawl's `saveJob` process, which saves the docs to supabase. So, we need to wait a bit before retrieving the data. That's why I implemented the `attempts` feature.

**Comment by KentHsu** [comment]
I see. I'm okay to merge this PR. I'll update the docs mentioned above. Thank you again for reviewing this PR!

**Comment by ericciarla** [comment]
Hey @KentHsu! Congrats on the merge 🚀 We would love to blast this on our social media channels on Wednesday. Could you possibly get the docs PR in by then?

Also what is your X/Twitter handle? We'd love to tag you!

**Comment by KentHsu** [comment]
Hi @ericciarla, Glad you ask. The docs is almost ready. I'll submit a PR later today. Meanwhile, I found there's an issue with the go-sdk module name, so I submit another PR to fix it. Please let me know if there's any problem. Thank you

Here's my X/Twitter handle: @kentchiahaohsu
Looking forward to it!

**Comment by ericciarla** [comment]
Thanks for the update @KentHsu and for getting the docs PR in! @rafaelsideguide can you look over this updated pull and merge?

**Pull request merged**
