### PR TITLE
Switching to AGPL - We Need Your Consent!

### PR DESCRIPTION
**Pull request by calebpeffer**
Hey everyone!

We've got some critical updates and need your help. As Firecrawl grows (we've crossed 2.6k stars!), we're thinking about sustainability and how to protect our project. We started with the Apache license because it's open and flexible. But, to ensure we can sustainably maintain this repository, we're switching to AGPL.

### Why AGPL?

We're moving to the GNU Affero General Public License (AGPL). It's still **open-source** and ensures that anyone who uses our software, even as a service over a network, shares their improvements. This helps everyone benefit and keeps the ecosystem fair. If we didn't use this license, companies could swoop in and sell their own versions of firecrawl without even contributing to the repository or attributing our collective work! 

### Here's What We Need from You:

If you've contributed to Firecrawl, please let us know if you're okay with switching your past contributions to AGPL. **Just drop a comment below saying, "I agree to relicense my contributions under the AGPL."**

@mdp @szepeviktor @bllchmbrs @rogerserper @mattzcarey @rafaelsideguide @nickscamara @ericciarla

**If we don't hear from you by June 6th, 2024, we'll have to revert your contributions.** 

### Questions?

Don't hesitate to ask if anything's unclear or if you have concerns. 

Thanks for joining us on the fire crawl rocketship 🔥 - we're excited to keep working to build the easiest way for good robots to access data on the web! 🤖 

Cheers,
Caleb

### CODE REVIEW

**Comment by bllchmbrs** [comment]
uf. Open source is fun.

All good by me.

**Comment by ericciarla** [comment]
Sounds good to me, I agree to relicense my contributions under the AGPL.

**Comment by mattzcarey** [comment]
I agree to relicense my contributions under the AGPL.

**Comment by nickscamara** [comment]
I agree to relicense my contributions under the AGPL

**Comment by rafaelsideguide** [comment]
I agree to relicense my contributions under the AGPL.

**Comment by szepeviktor** [comment]
I agree to relicense my contributions under the AGPL.

**Comment by rogerserper** [comment]
I agree to relicense my contributions under the AGPL

**Comment by calebpeffer** [comment]
Thanks everyone. We're now Licensed under AGPL!

**Pull request merged**
