### PR TITLE
feat: Actions

### PR DESCRIPTION
**Pull request by mogery**

### CODE REVIEW

**Comment by nickscamara** [comment]
- [ ] Pending fire-engine click fixes
- [ ] add to openapi
- [ ] Support for sdks (js done)

**Comment by mogery** [comment]
OpenAPI pr: https://github.com/hellofirecrawl/docs/pull/23

**Comment by mogery** [comment]
python sdk support doesn't need any changes theoretically

**Comment by nickscamara** [comment]
Will merge tomorrow!

**Review by nickscamara — APPROVED** [review]
lgtm!

**Pull request merged**
