### PR TITLE
fix(api): use builtin async timeout

### PR DESCRIPTION
**Pull request by twlite**
This PR replaces `await new Promise((..) => setTimeout(..))` with `await setTimeout(..)` from node's `timers/promises` module.

### CODE REVIEW

**Review by rafaelsideguide — CHANGES_REQUESTED** [review]
@twlite could you pls fix the typos? agan -> again

**Comment by twlite** [comment]
I have applied the suggestions, although I'm not sure why the PR is failing. Is it from my end or the tests ci has an issue?

**Comment by rafaelsideguide** [comment]
> I have applied the suggestions, although I'm not sure why the PR is failing. Is it from my end or the tests ci has an issue?

the ci/cd fails sometimes. I'll take a look.

**Comment by twlite** [comment]
alright, no worries

**Pull request closed without merging**
