### PR TITLE
Support for the 2 new actions

### PR DESCRIPTION
**Pull request by nickscamara**
`scrape` and `wait->selector`

### CODE REVIEW

**Comment by nickscamara** [comment]
- [ ] Need to bump a minor version on the node sdk

**Comment by ericciarla** [comment]
@rafaelsideguide can you look this over and merge when you have a sec?

**Comment by rafaelsideguide** [comment]
Found a bug.


When requesting with

```json
{
  "url": "firecrawl.dev",
  "actions": [
    {
      "type": "wait",
      "milliseconds": 2000,
      "selector": "#skip > section.py-20.bg-white > div > div.max-w-[94rem].mx-auto.space-y-6 > div:nth-child(1) > div:nth-child(1) > div:nth-child(3)"
    }
  ]
}
```
Got the response:
```json
{
  "success": true,
  "data": {
    "markdown": "",
    "metadata": {
      "sourceURL": "http://firecrawl.dev/",
      "error": "Failed to scrape the content, err: Error: Cannot wait for both milliseconds and selector",
      "statusCode": 500
    }
  }
}
```

But without the milliseconds:
```json
{
  "url": "firecrawl.dev",
  "actions": [
    {
      "type": "wait",
      "selector": "#skip > section.py-20.bg-white > div > div.max-w-[94rem].mx-auto.space-y-6 > div:nth-child(1) > div:nth-child(1) > div:nth-child(3)"
    }
  ]
}
```

Got another error:
```json
{
  "success": false,
  "error": "Bad Request",
  "details": [
    {
      "code": "invalid_union",
      "unionErrors": [
        {
          "issues": [
            {
              "code": "invalid_type",
              "expected": "number",
              "received": "undefined",
              "path": [
                "actions",
                0,
                "milliseconds"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "received": "wait",
              "code": "invalid_literal",
              "expected": "click",
              "path": [
                "actions",
                0,
                "type"
              ],
              "message": "Invalid literal value, expected \"click\""
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "received": "wait",
              "code": "invalid_literal",
              "expected": "screenshot",
              "path": [
                "actions",
                0,
                "type"
              ],
              "message": "Invalid literal value, expected \"screenshot\""
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "received": "wait",
              "code": "invalid_literal",
              "expected": "write",
              "path": [
                "actions",
                0,
                "type"
              ],
              "message": "Invalid literal value, expected \"write\""
            },
            {
              "code": "invalid_type",
              "expected": "string",
              "received": "undefined",
              "path": [
                "actions",
                0,
                "text"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "received": "wait",
              "code": "invalid_literal",
              "expected": "press",
              "path": [
                "actions",
                0,
                "type"
              ],
              "message": "Invalid literal value, expected \"press\""
            },
            {
              "code": "invalid_type",
              "expected": "string",
              "received": "undefined",
              "path": [
                "actions",
                0,
                "key"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "received": "wait",
              "code": "invalid_literal",
              "expected": "scroll",
              "path": [
                "actions",
                0,
                "type"
              ],
              "message": "Invalid literal value, expected \"scroll\""
            },
            {
              "expected": "'up' | 'down'",
              "received": "undefined",
              "code": "invalid_type",
              "path": [
                "actions",
                0,
                "direction"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "received": "wait",
              "code": "invalid_literal",
              "expected": "scrape",
              "path": [
                "actions",
                0,
                "type"
              ],
              "message": "Invalid literal value, expected \"scrape\""
            }
          ],
          "name": "ZodError"
        }
      ],
      "path": [
        "actions",
        0
      ],
      "message": "Invalid input"
    }
  ]
}
```

**Comment by rafaelsideguide** [comment]
> * [X]  Need to bump a minor version on the node sdk

bumped 1.7.3

**Review by rafaelsideguide — APPROVED** [review]

**Pull request merged**
