### PR TITLE
feat: Ability to forward headers to reliable providers for auth etc...

### PR DESCRIPTION
**Pull request by nickscamara**

### CODE REVIEW

**Comment by nickscamara** [comment]
Currently fire-engine and playwright.

**Comment by nickscamara** [comment]
closes #198

**Comment by nickscamara** [comment]
- [ ] Update docs

**Comment by ksbomj** [comment]
Hi @nickscamara,

Thank you for a good product! I trying to test your API, but my usecases are to crawl pages behind auth, so I need to pass cookies or authorization token, so pass headers in general. But it seems like passing headers doesn't work right now, I tried it over API endpoint and over this page https://docs.firecrawl.dev/api-reference/endpoint/scrape

I run a simple echo server that log incoming requests and put it behind ngrok for https connection (because your crawler does https even if I want http). When check logs of the server I don't see any custom header that were added to *pageOptions.headers*

Here how my request look like:
```bash
curl -X POST https://api.firecrawl.dev/v0/scrape -H 'Content-Type: application/json' -H 'Authorization: Bearer fc-8c...' -d '{"url":"https:\/\/6d33-11-85-45-23.ngrok-
free.app","pageOptions":{"headers":{"cookie":"s=m;"}}}'
```
Could please explain what I do wrong and what I can do in order to fix it?

Thanks

**Comment by nickscamara** [comment]
Hey @ksbomj, I believe it was an issue in our end. Just pushed a pr that fixes it https://github.com/mendableai/firecrawl/pull/331/files

Thank you so much for letting me know.

**Pull request merged**
