### PR TITLE
Add Docker Compose for easy self hosting

### PR DESCRIPTION
**Pull request by chand1012**
Added a super basic Docker Compose file for self hosting.

### CODE REVIEW

**Comment by rafaelsideguide** [comment]
Closes #82

**Comment by nickscamara** [comment]
- [ ] Document the env.local
- [ ] Add the rest of the documentation

**Comment by chand1012** [comment]
@nickscamara can you be more specific what documentation is missing?

**Comment by nickscamara** [comment]
@chand1012 oops sorry, we just need to add it to our external docs. I meant to cc @rafaelsideguide but forgot.

The pr looks good though. Thank you!

**Comment by rafaelsideguide** [comment]
@chand1012 I did some improvements on the docs and envs but I got some connection errors while running the containers. Maybe the `network` is missing on compose file?

```
firecrawl-api-1                 | Error: connect ECONNREFUSED 127.0.0.1:6379
firecrawl-api-1 exited with code 1
firecrawl-worker-1           | Web scraper queue created
firecrawl-worker-1           | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
```

**Review by rafaelsideguide — CHANGES_REQUESTED** [review]
@chand1012 I did some improvements on the docs and envs but I got some connection errors while running the containers. Maybe the `network` is missing on compose file?

```
firecrawl-api-1                 | Error: connect ECONNREFUSED 127.0.0.1:6379
firecrawl-api-1 exited with code 1
firecrawl-worker-1           | Web scraper queue created
firecrawl-worker-1           | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by chand1012** [comment]
@rafaelsideguide try it now

**Review by rafaelsideguide — APPROVED** [review]
I did some minor changes and it's seem to be working ok! Approved

**Comment by rafaelsideguide** [comment]
Awesome job @chand1012

**Comment by chand1012** [comment]
I agree to relicense my contributions to the AGPL.

**Pull request merged**
