### PR TITLE
Cancel Job Route

### LINKED ISSUE #106: [Feat] Cancel job route
"Provide an API to cancel jobs, especially for expensive ones. Setting the default limit at 10,000 could potentially break someone’s bank."

Suggested by @by12380 on Discord

### PR DESCRIPTION
**Pull request by nickscamara**
closes #106

Notes: Bull doesnt allow to cancel active jobs.

Design decision: we mark the job as failed when someone cancels, and we stop the scraping process (which is the actual expensive process). We bill them as soon as they cancel, even if some promises are not resolved resulting in them getting more from what they paid (totally cool!)

I think this works fairly well for now. @rafaelsideguide would love a look over.

### CODE REVIEW

**Comment by nickscamara** [comment]
I ended up upgrading our fly setup here. Feel free to ignore.

**Review by rafaelsideguide — CHANGES_REQUESTED** [review]
Introduced a 500 error on /scrape and /search. Also, the cancel test is not passing.

 - E2E Tests for API Routes › POST /v0/scrape › should return a successful response with a valid preview token

    expect(response.statusCode).toBe(200) // Object.is equality

    Expected: 200
    Received: 500

 - E2E Tests for API Routes › POST /v0/scrape › should return a successful response with a valid API key

    expect(response.statusCode).toBe(200) 

    Expected: 200
    Received: 500

 - E2E Tests for API Routes › POST /v0/search › should return a successful response with a valid API key

    expect(response.statusCode).toBe(200);

    Expected: 200
    Received: 500

 - E2E Tests for API Routes › If someone cancels a crawl job, it should turn into failed status

    expect(completedResponse.body.partial_data?.length ?? 0).toBeLessThanOrEqual(completedResponse.body.data?.length ?? 0)

    Expected: <= 0
    Received:    40

 - E2E Tests for API Routes › POST /v0/scrape with LLM Extraction › should extract data using LLM extraction mode

    expect(response.statusCode).toBe(200) // Object.is equality

    Expected: 200
    Received: 500

**Comment by nickscamara** [comment]
Thanks @rafaelsideguide, pushed a fix

**Comment by nickscamara** [comment]
- [ ] Add to docs

**Pull request merged**
