### PR TITLE
[Feat] Added llama parser sdk and timeout for scrape

### LINKED ISSUE #413: [BUG] Allow scraping of files (like PDFs) that are more than 10mb
We just lost a customer because we weren't able to scrape a pdf on the tesla website. 

For pdf files, we have a limit of 10mb (right @rafaelsideguide, you mentioned this to me via slack) regarding this discussion https://github.com/mendableai/firecrawl/discussions/51#discussioncomment-9941986

If possible, we need to get around this limit so customers aren't left in the dark as to why a particular PDF wasn't processed

### PR DESCRIPTION
**Pull request by rafaelsideguide**
Updated `pdfProcessor` for using llama parser TS SDK. Looks better now. Also added timeout so the user can wait for bigger PDF files.

Tested with:
```
POST http://localhost:3002/v0/scrape HTTP/1.1
Authorization: Bearer fc-***
content-type: application/json

{
  "url": "https://www.tesla.com/ns_videos/2023-tesla-impact-report.pdf",
  "timeout": 300000
}
```

This file takes ~60 seconds to parse.

Closes #413

### CODE REVIEW

**Comment by nickscamara** [comment]
Awesome stuff @rafaelsideguide! Quick q, wouldnt this internal /scrape timeout conflict with the one we have on the endpoint? Meaning if they are the same, it would cause the request to time out if it used all the time available right?

**Comment by rafaelsideguide** [comment]
@nickscamara added check for the remaining time on each scrape attempt

**Review by nickscamara — APPROVED** [review]

**Comment by nickscamara** [comment]
Looks good @rafaelsideguide!

**Comment by nickscamara** [comment]
@mogery will rework this in in the new refactored version!

**Pull request closed without merging**
