### PR TITLE
feat: add timeout param to scrape and crawl

### PR DESCRIPTION
**Pull request by ezhil56x**
/claim #59

### CODE REVIEW

**Comment by rafaelsideguide** [comment]
@ezhil56x awesome job! Could you add some e2e tests?

**Comment by ezhil56x** [comment]
@rafaelsideguide 
Should be have a default timeout or is it not required?

**Comment by ezhil56x** [comment]
@rafaelsideguide 
Can I get a review once?

**Comment by rafaelsideguide** [comment]
@ezhil56x
for `/scrape` the default should be 20 seconds
for `/crawl` the default should be `this.limit` x 20 seconds

**Comment by ezhil56x** [comment]
@rafaelsideguide 
Done!

**Comment by rafaelsideguide** [comment]
@ezhil56x crawl is not working properly. I added a test on `e2e_withAuth` with how it's supposed to work.

**Comment by ezhil56x** [comment]
@rafaelsideguide
Updated my PR

**Comment by rafaelsideguide** [comment]
The v0/crawl test does not pass. The timeout function runs, but the job is still running, so it crawls the pages and returns a success response. This should not happen.

Captura de Tela 2024-04-29 às 09 18 04

**Comment by nickscamara** [comment]
@rafaelsideguide we should also support partial docs on the webhook, just got a customer request for that!

**Comment by nickscamara** [comment]
@ezhil56x thanks for the initial contribution, unfortunately we are closing this for now as we will need some architectural changes to be able to do timeout in the crawl reliably.

**Pull request closed without merging**
